Repository auth0/laravel-auth0, pull requests merged in 2019-06, with the labels that each got.

#128 Return null instead of false in Auth0UserProvider.
  src/Auth0/Login/Auth0UserProvider.php
Labels: CH: Changed

#131 Fix cachehandler resolving issues
  src/Auth0/Login/Auth0Service.php
Labels: CH: Fixed

#132 Change private properties to protected
  src/Auth0/Login/Auth0User.php
Labels: CH: Changed, tiny
