Repository auth0/laravel-auth0, pull requests merged in 2020-04, with the labels that each got.

#174 Fix Laravel session management
  .DS_Store
  src/Auth0/Login/LaravelSessionStore.php
Labels: CH: Fixed

#175 laravel 7 support
  composer.json
Labels: CH: Added, tiny

#176 Use array for Auth0JWTUser and add repo return types
  src/Auth0/Login/Auth0JWTUser.php
  src/Auth0/Login/Auth0Service.php
  src/Auth0/Login/Auth0User.php
  src/Auth0/Login/Contract/Auth0UserRepository.php
  src/Auth0/Login/Repository/Auth0UserRepository.php
  tests/Auth0ServiceTest.php
  tests/Unit/Auth0JWTUserTest.php
Labels: CH: Changed, small

#179 Merge 6.0.0 into master
  .DS_Store
  .phpcs.xml.dist
  CHANGELOG.md
  README.md
  composer.json
  phpunit.xml.dist
  src/Auth0/Login/Auth0JWTUser.php
  src/Auth0/Login/Auth0Service.php
  src/Auth0/Login/Auth0User.php
  src/Auth0/Login/Contract/Auth0UserRepository.php
  src/Auth0/Login/LaravelCacheWrapper.php
  src/Auth0/Login/LaravelSessionStore.php
  src/Auth0/Login/LoginServiceProvider.php
  src/Auth0/Login/Repository/Auth0UserRepository.php
  tests/Auth0ServiceTest.php
  tests/Unit/Auth0JWTUserTest.php
Labels: tiny

#180 Update Snyk reported name
  .circleci/config.yml
Labels: tiny

#183 Fix access token validation
  src/Auth0/Login/Auth0Service.php
  tests/Auth0ServiceTest.php
  tests/Unit/Auth0ServiceUnitTest.php
Labels: CH: Fixed, small

#184 Release 6.0.1
  CHANGELOG.md
  README.md
  composer.json
  src/Auth0/Login/LoginServiceProvider.php
Labels: small
