Repository auth0/laravel-auth0, pull requests merged in 2023-12, with the labels that each got.

#434 fix: `CacheBridgeAbstract::save()` not assigning value to cache when cache hit mises
  src/Bridges/CacheBridgeAbstract.php
  tests/Unit/Bridges/CacheBridgeTest.php
Labels: Scope: Bug

#435 feat(SDK-4732): Implement support for Back-Channel Logout
  composer.json
  config/auth0.php
  docs/BackchannelLogout.md
  docs/Configuration.md
  src/Configuration.php
  src/Entities/InstanceEntityAbstract.php
  tests/Unit/ServiceTest.php
Labels: Scope: Improvement

#436 feat: Configurable Route Paths
  config/auth0.php
  rector.php
  src/Configuration.php
  src/Controllers/CallbackControllerAbstract.php
  src/Controllers/LoginControllerAbstract.php
  src/Controllers/LogoutControllerAbstract.php
  src/ServiceAbstract.php
  src/ServiceProviderAbstract.php
  tests/Unit/ConfigurationTest.php
Labels: Scope: Improvement

#437 Release 7.12.0
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  docs/Installation.md
  src/ServiceAbstract.php
Labels: Scope: Release

#438 ci(release): Add `.version` file
  .shiprc
  .version
Labels: Scope: Maintenance
